server:
  port: 8082
  servlet:
    context-path: /admin

spring:
  application:
    name: musinsa-assignment-backoffice

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

  datasource:
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    url: jdbc:log4jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password: qwer
    platform: h2

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  swagger-ui:
    path: /swagger-ui.html
    enable: true
    groups-order: DESC
    operations-sorter: method
    tags-sorter: method
  cache:
    disabled: true
  model-and-view-allowwd: false
