DROP TABLE if EXISTS "PRODUCT";
DROP TABLE if EXISTS BRAND;
DROP TABLE if EXISTS "CATEGORY";


CREATE TABLE BRAND (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE "CATEGORY" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE "PRODUCT" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand_id INT,
    category_id INT,
    price BIGINT,
    FOREIGN KEY (brand_id) REFERENCES Brand(id),
    FOREIGN KEY (category_id) REFERENCES Category(id)
);